### ISSUE TITLE
Socialite Manager Error

### ISSUE THREAD

**Issue by hai-ru** [acacha/laravel-social#13]
I was install laravel social look like documentation and i install social media app facebook but if i want to acess its give error message : 
"Type error: Argument 1 passed to Laravel\Socialite\SocialiteManager::formatRedirectUrl() must be of the type array, null given, called in

![scerror](https://user-images.githubusercontent.com/24634668/33089717-161dadba-cf24-11e7-9ead-53d542295c9d.png)

I used laravel 5.5 latest

Apache version: Apache/2.4.29
PHP version: 7.1.9
MySQL version: 10.1.28-MariaDB

**Comment by maurino72** [comment]
Same issue! Have you resolve this?

**Comment by mariusrestua** [comment]
Hi, this post is pretty outdated but for the people who still have the problem.

As you can see, it expects to have an array. But you receives null.

Here's a possible solution:
1. If you want to create a driver (for e.g. Facebook), then you will need your "client_id" and "client_secret" you will need it for communicating with the Facebook API. 

**To get your keys: go to your [facebook app](https://developers.facebook.com/apps) > settings > basic.**

You will see your App ID and App Secret. Other third parties like Google also have a client id/secret.

2. Now you have your App-ID/Secret, go to your Laravel project and search for `config/services.php`. 

3. Because you want to create a Facebook driver, it expects to have 'facebook' credentials (as array) in `config/servies.php`.  So it means that:
- You didn't make credentials for the 'facebook' driver.
- Or the credentials for the 'facebook' driver is incomplete (too few arguments).

4. To solve this, add:
```   
 'facebook' => [
        'client_id' => '1234567890', //add your app-id here
        'client_secret' => '1234567890', //add your secret-id here
        'redirect' => ''
    ],
```
(optional) _You can also do this:_ 
```
    'facebook' => [
        'client_id' => env('FACEBOOK_CLIENT_ID'),
        'client_secret' => env('FACEBOOK_SECRET_ID'),
        'redirect' => ''
    ],
```
Then go to your .env and add your app/secret-id.
```
FACEBOOK_CLIENT_ID="1234567890" #add your app-id here
FACEBOOK_SECRET_ID="1234567890" #add your secret-id here
```

Hopefully this will solve your problem 👍

**Comment by devrizwanali** [comment]
run the command:
 **php artisan config:clear**
this work for me :)

**Comment by ghost** [comment]
thank you broo
